[versions]
# Gradle & Plugins
agp = "8.13.1"
ksp = "2.2.21-2.0.4"

# Kotlin & Coroutines
kotlin = "2.2.21"
kotlinxCoroutinesCore = "1.10.2"
kotlinxSerializationJson = "1.9.0"

# AndroidX Core & AppCompat
coreKtx = "1.17.0"
activityCompose = "1.12.0"

# Jetpack Compose
composeBom = "2025.11.01"
constraintlayoutCompose = "1.1.1"
material = "1.13.0"
material3Android = "1.4.0"

# Lifecycle
lifecycleRuntimeKtx = "2.10.0"
lifecycleViewmodelSavedstate = "2.10.0"

# Navigation
navigationCompose = "2.9.6"
navigationCommonAndroid = "2.9.6"
navigationRuntime = "2.9.6"
hiltNavigationCompose = "1.3.0"

# Hilt (DI)
hiltAndroid = "2.57.2"

# coil
coilBom = "2.7.0"

# Data Persistence (Room, Datastore)
roomRuntime = "2.8.4"
datastorePreferences = "1.2.0"
datastoreCoreAndroid = "1.2.0"

# Networking (Ktor)
ktorVersion = "3.3.3"

# Test
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"

# Accompanist permission
accompanistPermissions = "0.37.3"

# KeyStore
securityCrypto = "1.1.0"

# Glance
glanceAppwidget = "1.1.1"

# Firebase
firebaseBom = "34.6.0"
credentialManager = "1.5.0"
googleid = "1.1.1"

################################################################

[libraries]

# Android Core
androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayoutCompose" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }

# Kotlin & Coroutines
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
kotlinx-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

# Hilt (DI)
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroid" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltAndroid" }
hilt-core = { module = "com.google.dagger:hilt-core", version.ref = "hiltAndroid" }

# Lifecycle (Viewmodel, SavedState)
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-savedstate = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-savedstate", version.ref = "lifecycleViewmodelSavedstate" }

# Jetpack Compose
## Core UI
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }

## Navigation
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-navigation-common-android = { group = "androidx.navigation", name = "navigation-common-android", version.ref = "navigationCommonAndroid" }
androidx-navigation-runtime = { group = "androidx.navigation", name = "navigation-runtime", version.ref = "navigationRuntime" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }

## Material Components
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-material3-android = { group = "androidx.compose.material3", name = "material3-android", version.ref = "material3Android" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }

## Tooling & Preveiw
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }

# Room
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomRuntime" }
androidx-room-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }

# Coil
coil-bom = { module = "io.coil-kt:coil-bom", version.ref = "coilBom" }
coil-compose = { module = "io.coil-kt:coil-compose" }
coil-svg = { module = "io.coil-kt:coil-svg" }
coil-gif = { module = "io.coil-kt:coil-gif" }
coil-video = { module = "io.coil-kt:coil-video" }

# Test
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

# Datastore
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-datastore-core-android = { group = "androidx.datastore", name = "datastore-core-android", version.ref = "datastoreCoreAndroid" }

# Ktor
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktorVersion" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktorVersion" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktorVersion" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktorVersion" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktorVersion" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktorVersion" }

# Accompanist-permissions
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }

# KeyStore
androidx-security-crypto = { module = "androidx.security:security-crypto", version.ref = "securityCrypto" }

# Glance
androidx-glance-appwidget = { module = "androidx.glance:glance-appwidget", version.ref = "glanceAppwidget" }

# Firebase
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth" }
firebase-functions = { module= "com.google.firebase:firebase-functions"}
firebase-firestore = { module = "com.google.firebase:firebase-firestore" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging"}

# Credential Manager
credential-manager = { group = "androidx.credentials", name = "credentials", version.ref = "credentialManager" }
credential-manager-google = { group = "androidx.credentials", name = "credentials-play-services-auth", version.ref = "credentialManager" }
googleid = { group = "com.google.android.libraries.identity.googleid", name = "googleid", version.ref = "googleid" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
devtoolsKsp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid" }